version: '3.9'
services:
  db:
    container_name: ${DATABASE_HOST}
    image: postgres
    env_file: .env
    restart: unless-stopped
    environment:
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_DB: $DATABASE_NAME
    ports:
      - $DATABASE_PORT:$DATABASE_PORT
    networks:
      - app_network
    volumes:
      - db_pg_volume:/var/lib/postgres

  api:
    container_name: ${PROJECT_NAME}_api
    restart: unless-stopped
    env_file: .env
    build: .
    depends_on:
      - db
    ports:
      - ${API_PORT}:${API_PORT}
    expose:
      - ${API_PORT}
    networks:
      - app_network

networks:
  app_network:

volumes:
  db_pg_volume:
